//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50522.1
// 
namespace Rohi.EBinder.Sync.WebsReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public enum CustomizedPageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uncustomized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customized = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="WebsReference.WebsSoap")]
    public interface WebsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWebCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebCollectionResponse> GetWebCollectionAsync(Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebResponse> GetWebAsync(Rohi.EBinder.Sync.WebsReference.GetWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListTemplates", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetListTemplatesResponse> GetListTemplatesAsync(Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetAllSubWebCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionResponse> GetAllSubWebCollectionAsync(Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/WebUrlFromPageUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlResponse> WebUrlFromPageUrlAsync(Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypesResponse> GetContentTypesAsync(Rohi.EBinder.Sync.WebsReference.GetContentTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentType", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypeResponse> GetContentTypeAsync(Rohi.EBinder.Sync.WebsReference.GetContentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CreateContentType", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CreateContentTypeResponse> CreateContentTypeAsync(Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentType", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeResponse> UpdateContentTypeAsync(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteContentType", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.DeleteContentTypeResponse> DeleteContentTypeAsync(Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentResponse> UpdateContentTypeXmlDocumentAsync(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RemoveContentTypeXmlDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentResponse> RemoveContentTypeXmlDocumentAsync(Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetColumnsResponse> GetColumnsAsync(Rohi.EBinder.Sync.WebsReference.GetColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateColumnsResponse> UpdateColumnsAsync(Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetCustomizedPageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusResponse> GetCustomizedPageStatusAsync(Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertFileContentStream", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamResponse> RevertFileContentStreamAsync(Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertAllFileContentStreams", ReplyAction="*")]
        System.Threading.Tasks.Task RevertAllFileContentStreamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CustomizeCss", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CustomizeCssResponse> CustomizeCssAsync(Rohi.EBinder.Sync.WebsReference.CustomizeCssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertCss", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertCssResponse> RevertCssAsync(Rohi.EBinder.Sync.WebsReference.RevertCssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetActivatedFeatures", ReplyAction="*")]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesResponse> GetActivatedFeaturesAsync(Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequestBody Body;
        
        public GetWebCollectionRequest() {
        }
        
        public GetWebCollectionRequest(Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWebCollectionRequestBody {
        
        public GetWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetWebCollectionResponseBody Body;
        
        public GetWebCollectionResponse() {
        }
        
        public GetWebCollectionResponse(Rohi.EBinder.Sync.WebsReference.GetWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebCollectionResult;
        
        public GetWebCollectionResponseBody() {
        }
        
        public GetWebCollectionResponseBody(System.Xml.Linq.XElement GetWebCollectionResult) {
            this.GetWebCollectionResult = GetWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeb", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetWebRequestBody Body;
        
        public GetWebRequest() {
        }
        
        public GetWebRequest(Rohi.EBinder.Sync.WebsReference.GetWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string webUrl;
        
        public GetWebRequestBody() {
        }
        
        public GetWebRequestBody(string webUrl) {
            this.webUrl = webUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetWebResponseBody Body;
        
        public GetWebResponse() {
        }
        
        public GetWebResponse(Rohi.EBinder.Sync.WebsReference.GetWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebResult;
        
        public GetWebResponseBody() {
        }
        
        public GetWebResponseBody(System.Xml.Linq.XElement GetWebResult) {
            this.GetWebResult = GetWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplates", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequestBody Body;
        
        public GetListTemplatesRequest() {
        }
        
        public GetListTemplatesRequest(Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListTemplatesRequestBody {
        
        public GetListTemplatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplatesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetListTemplatesResponseBody Body;
        
        public GetListTemplatesResponse() {
        }
        
        public GetListTemplatesResponse(Rohi.EBinder.Sync.WebsReference.GetListTemplatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListTemplatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetListTemplatesResult;
        
        public GetListTemplatesResponseBody() {
        }
        
        public GetListTemplatesResponseBody(System.Xml.Linq.XElement GetListTemplatesResult) {
            this.GetListTemplatesResult = GetListTemplatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequestBody Body;
        
        public GetAllSubWebCollectionRequest() {
        }
        
        public GetAllSubWebCollectionRequest(Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSubWebCollectionRequestBody {
        
        public GetAllSubWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionResponseBody Body;
        
        public GetAllSubWebCollectionResponse() {
        }
        
        public GetAllSubWebCollectionResponse(Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetAllSubWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAllSubWebCollectionResult;
        
        public GetAllSubWebCollectionResponseBody() {
        }
        
        public GetAllSubWebCollectionResponseBody(System.Xml.Linq.XElement GetAllSubWebCollectionResult) {
            this.GetAllSubWebCollectionResult = GetAllSubWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrl", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequestBody Body;
        
        public WebUrlFromPageUrlRequest() {
        }
        
        public WebUrlFromPageUrlRequest(Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pageUrl;
        
        public WebUrlFromPageUrlRequestBody() {
        }
        
        public WebUrlFromPageUrlRequestBody(string pageUrl) {
            this.pageUrl = pageUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrlResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlResponseBody Body;
        
        public WebUrlFromPageUrlResponse() {
        }
        
        public WebUrlFromPageUrlResponse(Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebUrlFromPageUrlResult;
        
        public WebUrlFromPageUrlResponseBody() {
        }
        
        public WebUrlFromPageUrlResponseBody(string WebUrlFromPageUrlResult) {
            this.WebUrlFromPageUrlResult = WebUrlFromPageUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypes", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetContentTypesRequestBody Body;
        
        public GetContentTypesRequest() {
        }
        
        public GetContentTypesRequest(Rohi.EBinder.Sync.WebsReference.GetContentTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContentTypesRequestBody {
        
        public GetContentTypesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetContentTypesResponseBody Body;
        
        public GetContentTypesResponse() {
        }
        
        public GetContentTypesResponse(Rohi.EBinder.Sync.WebsReference.GetContentTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypesResult;
        
        public GetContentTypesResponseBody() {
        }
        
        public GetContentTypesResponseBody(System.Xml.Linq.XElement GetContentTypesResult) {
            this.GetContentTypesResult = GetContentTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetContentTypeRequestBody Body;
        
        public GetContentTypeRequest() {
        }
        
        public GetContentTypeRequest(Rohi.EBinder.Sync.WebsReference.GetContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public GetContentTypeRequestBody() {
        }
        
        public GetContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetContentTypeResponseBody Body;
        
        public GetContentTypeResponse() {
        }
        
        public GetContentTypeResponse(Rohi.EBinder.Sync.WebsReference.GetContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypeResult;
        
        public GetContentTypeResponseBody() {
        }
        
        public GetContentTypeResponseBody(System.Xml.Linq.XElement GetContentTypeResult) {
            this.GetContentTypeResult = GetContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequestBody Body;
        
        public CreateContentTypeRequest() {
        }
        
        public CreateContentTypeRequest(Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        public CreateContentTypeRequestBody() {
        }
        
        public CreateContentTypeRequestBody(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            this.displayName = displayName;
            this.parentType = parentType;
            this.newFields = newFields;
            this.contentTypeProperties = contentTypeProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.CreateContentTypeResponseBody Body;
        
        public CreateContentTypeResponse() {
        }
        
        public CreateContentTypeResponse(Rohi.EBinder.Sync.WebsReference.CreateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateContentTypeResult;
        
        public CreateContentTypeResponseBody() {
        }
        
        public CreateContentTypeResponseBody(string CreateContentTypeResult) {
            this.CreateContentTypeResult = CreateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequestBody Body;
        
        public UpdateContentTypeRequest() {
        }
        
        public UpdateContentTypeRequest(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateContentTypeRequestBody() {
        }
        
        public UpdateContentTypeRequestBody(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.contentTypeId = contentTypeId;
            this.contentTypeProperties = contentTypeProperties;
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateContentTypeResponseBody Body;
        
        public UpdateContentTypeResponse() {
        }
        
        public UpdateContentTypeResponse(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeResult;
        
        public UpdateContentTypeResponseBody() {
        }
        
        public UpdateContentTypeResponseBody(System.Xml.Linq.XElement UpdateContentTypeResult) {
            this.UpdateContentTypeResult = UpdateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequestBody Body;
        
        public DeleteContentTypeRequest() {
        }
        
        public DeleteContentTypeRequest(Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public DeleteContentTypeRequestBody() {
        }
        
        public DeleteContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.DeleteContentTypeResponseBody Body;
        
        public DeleteContentTypeResponse() {
        }
        
        public DeleteContentTypeResponse(Rohi.EBinder.Sync.WebsReference.DeleteContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteContentTypeResult;
        
        public DeleteContentTypeResponseBody() {
        }
        
        public DeleteContentTypeResponseBody(System.Xml.Linq.XElement DeleteContentTypeResult) {
            this.DeleteContentTypeResult = DeleteContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequestBody Body;
        
        public UpdateContentTypeXmlDocumentRequest() {
        }
        
        public UpdateContentTypeXmlDocumentRequest(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement newDocument;
        
        public UpdateContentTypeXmlDocumentRequestBody() {
        }
        
        public UpdateContentTypeXmlDocumentRequestBody(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            this.contentTypeId = contentTypeId;
            this.newDocument = newDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentResponseBody Body;
        
        public UpdateContentTypeXmlDocumentResponse() {
        }
        
        public UpdateContentTypeXmlDocumentResponse(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult;
        
        public UpdateContentTypeXmlDocumentResponseBody() {
        }
        
        public UpdateContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult) {
            this.UpdateContentTypeXmlDocumentResult = UpdateContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequestBody Body;
        
        public RemoveContentTypeXmlDocumentRequest() {
        }
        
        public RemoveContentTypeXmlDocumentRequest(Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentUri;
        
        public RemoveContentTypeXmlDocumentRequestBody() {
        }
        
        public RemoveContentTypeXmlDocumentRequestBody(string contentTypeId, string documentUri) {
            this.contentTypeId = contentTypeId;
            this.documentUri = documentUri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentResponseBody Body;
        
        public RemoveContentTypeXmlDocumentResponse() {
        }
        
        public RemoveContentTypeXmlDocumentResponse(Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult;
        
        public RemoveContentTypeXmlDocumentResponseBody() {
        }
        
        public RemoveContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult) {
            this.RemoveContentTypeXmlDocumentResult = RemoveContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetColumnsRequestBody Body;
        
        public GetColumnsRequest() {
        }
        
        public GetColumnsRequest(Rohi.EBinder.Sync.WebsReference.GetColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnsRequestBody {
        
        public GetColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetColumnsResponseBody Body;
        
        public GetColumnsResponse() {
        }
        
        public GetColumnsResponse(Rohi.EBinder.Sync.WebsReference.GetColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetColumnsResult;
        
        public GetColumnsResponseBody() {
        }
        
        public GetColumnsResponseBody(System.Xml.Linq.XElement GetColumnsResult) {
            this.GetColumnsResult = GetColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequestBody Body;
        
        public UpdateColumnsRequest() {
        }
        
        public UpdateColumnsRequest(Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateColumnsRequestBody() {
        }
        
        public UpdateColumnsRequestBody(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.UpdateColumnsResponseBody Body;
        
        public UpdateColumnsResponse() {
        }
        
        public UpdateColumnsResponse(Rohi.EBinder.Sync.WebsReference.UpdateColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateColumnsResult;
        
        public UpdateColumnsResponseBody() {
        }
        
        public UpdateColumnsResponseBody(System.Xml.Linq.XElement UpdateColumnsResult) {
            this.UpdateColumnsResult = UpdateColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequestBody Body;
        
        public GetCustomizedPageStatusRequest() {
        }
        
        public GetCustomizedPageStatusRequest(Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public GetCustomizedPageStatusRequestBody() {
        }
        
        public GetCustomizedPageStatusRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatusResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusResponseBody Body;
        
        public GetCustomizedPageStatusResponse() {
        }
        
        public GetCustomizedPageStatusResponse(Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Rohi.EBinder.Sync.WebsReference.CustomizedPageStatus GetCustomizedPageStatusResult;
        
        public GetCustomizedPageStatusResponseBody() {
        }
        
        public GetCustomizedPageStatusResponseBody(Rohi.EBinder.Sync.WebsReference.CustomizedPageStatus GetCustomizedPageStatusResult) {
            this.GetCustomizedPageStatusResult = GetCustomizedPageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStream", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequestBody Body;
        
        public RevertFileContentStreamRequest() {
        }
        
        public RevertFileContentStreamRequest(Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertFileContentStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public RevertFileContentStreamRequestBody() {
        }
        
        public RevertFileContentStreamRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStreamResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamResponseBody Body;
        
        public RevertFileContentStreamResponse() {
        }
        
        public RevertFileContentStreamResponse(Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertFileContentStreamResponseBody {
        
        public RevertFileContentStreamResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.CustomizeCssRequestBody Body;
        
        public CustomizeCssRequest() {
        }
        
        public CustomizeCssRequest(Rohi.EBinder.Sync.WebsReference.CustomizeCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CustomizeCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public CustomizeCssRequestBody() {
        }
        
        public CustomizeCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.CustomizeCssResponseBody Body;
        
        public CustomizeCssResponse() {
        }
        
        public CustomizeCssResponse(Rohi.EBinder.Sync.WebsReference.CustomizeCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CustomizeCssResponseBody {
        
        public CustomizeCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RevertCssRequestBody Body;
        
        public RevertCssRequest() {
        }
        
        public RevertCssRequest(Rohi.EBinder.Sync.WebsReference.RevertCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public RevertCssRequestBody() {
        }
        
        public RevertCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.RevertCssResponseBody Body;
        
        public RevertCssResponse() {
        }
        
        public RevertCssResponse(Rohi.EBinder.Sync.WebsReference.RevertCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertCssResponseBody {
        
        public RevertCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeatures", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequestBody Body;
        
        public GetActivatedFeaturesRequest() {
        }
        
        public GetActivatedFeaturesRequest(Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActivatedFeaturesRequestBody {
        
        public GetActivatedFeaturesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeaturesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesResponseBody Body;
        
        public GetActivatedFeaturesResponse() {
        }
        
        public GetActivatedFeaturesResponse(Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetActivatedFeaturesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActivatedFeaturesResult;
        
        public GetActivatedFeaturesResponseBody() {
        }
        
        public GetActivatedFeaturesResponseBody(string GetActivatedFeaturesResult) {
            this.GetActivatedFeaturesResult = GetActivatedFeaturesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebsSoapChannel : Rohi.EBinder.Sync.WebsReference.WebsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebsSoapClient : System.ServiceModel.ClientBase<Rohi.EBinder.Sync.WebsReference.WebsSoap>, Rohi.EBinder.Sync.WebsReference.WebsSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebsSoapClient() : 
                base(WebsSoapClient.GetDefaultBinding(), WebsSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.WebsSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebsSoapClient.GetBindingForEndpoint(endpointConfiguration), WebsSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebCollectionResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetWebCollectionAsync(Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequest request) {
            return base.Channel.GetWebCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebCollectionResponse> GetWebCollectionAsync() {
            Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetWebCollectionRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetWebCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetWebAsync(Rohi.EBinder.Sync.WebsReference.GetWebRequest request) {
            return base.Channel.GetWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetWebResponse> GetWebAsync(string webUrl) {
            Rohi.EBinder.Sync.WebsReference.GetWebRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetWebRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetWebRequestBody();
            inValue.Body.webUrl = webUrl;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetWebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetListTemplatesResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetListTemplatesAsync(Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequest request) {
            return base.Channel.GetListTemplatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetListTemplatesResponse> GetListTemplatesAsync() {
            Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetListTemplatesRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetListTemplatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetAllSubWebCollectionAsync(Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequest request) {
            return base.Channel.GetAllSubWebCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionResponse> GetAllSubWebCollectionAsync() {
            Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetAllSubWebCollectionRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetAllSubWebCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.WebUrlFromPageUrlAsync(Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequest request) {
            return base.Channel.WebUrlFromPageUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlResponse> WebUrlFromPageUrlAsync(string pageUrl) {
            Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequest inValue = new Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.WebUrlFromPageUrlRequestBody();
            inValue.Body.pageUrl = pageUrl;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).WebUrlFromPageUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypesResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetContentTypesAsync(Rohi.EBinder.Sync.WebsReference.GetContentTypesRequest request) {
            return base.Channel.GetContentTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypesResponse> GetContentTypesAsync() {
            Rohi.EBinder.Sync.WebsReference.GetContentTypesRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetContentTypesRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetContentTypesRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetContentTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypeResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetContentTypeAsync(Rohi.EBinder.Sync.WebsReference.GetContentTypeRequest request) {
            return base.Channel.GetContentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetContentTypeResponse> GetContentTypeAsync(string contentTypeId) {
            Rohi.EBinder.Sync.WebsReference.GetContentTypeRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetContentTypeRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetContentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CreateContentTypeResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.CreateContentTypeAsync(Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequest request) {
            return base.Channel.CreateContentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CreateContentTypeResponse> CreateContentTypeAsync(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequest inValue = new Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.CreateContentTypeRequestBody();
            inValue.Body.displayName = displayName;
            inValue.Body.parentType = parentType;
            inValue.Body.newFields = newFields;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).CreateContentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.UpdateContentTypeAsync(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequest request) {
            return base.Channel.UpdateContentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeResponse> UpdateContentTypeAsync(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequest inValue = new Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.UpdateContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).UpdateContentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.DeleteContentTypeResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.DeleteContentTypeAsync(Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequest request) {
            return base.Channel.DeleteContentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.DeleteContentTypeResponse> DeleteContentTypeAsync(string contentTypeId) {
            Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequest inValue = new Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.DeleteContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).DeleteContentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.UpdateContentTypeXmlDocumentAsync(Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequest request) {
            return base.Channel.UpdateContentTypeXmlDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentResponse> UpdateContentTypeXmlDocumentAsync(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequest inValue = new Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.UpdateContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.newDocument = newDocument;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).UpdateContentTypeXmlDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.RemoveContentTypeXmlDocumentAsync(Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequest request) {
            return base.Channel.RemoveContentTypeXmlDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentResponse> RemoveContentTypeXmlDocumentAsync(string contentTypeId, string documentUri) {
            Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequest inValue = new Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.RemoveContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.documentUri = documentUri;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).RemoveContentTypeXmlDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetColumnsResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetColumnsAsync(Rohi.EBinder.Sync.WebsReference.GetColumnsRequest request) {
            return base.Channel.GetColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetColumnsResponse> GetColumnsAsync() {
            Rohi.EBinder.Sync.WebsReference.GetColumnsRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetColumnsRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetColumnsRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetColumnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateColumnsResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.UpdateColumnsAsync(Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequest request) {
            return base.Channel.UpdateColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.UpdateColumnsResponse> UpdateColumnsAsync(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequest inValue = new Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.UpdateColumnsRequestBody();
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).UpdateColumnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetCustomizedPageStatusAsync(Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequest request) {
            return base.Channel.GetCustomizedPageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusResponse> GetCustomizedPageStatusAsync(string fileUrl) {
            Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetCustomizedPageStatusRequestBody();
            inValue.Body.fileUrl = fileUrl;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetCustomizedPageStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.RevertFileContentStreamAsync(Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequest request) {
            return base.Channel.RevertFileContentStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamResponse> RevertFileContentStreamAsync(string fileUrl) {
            Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequest inValue = new Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.RevertFileContentStreamRequestBody();
            inValue.Body.fileUrl = fileUrl;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).RevertFileContentStreamAsync(inValue);
        }
        
        public System.Threading.Tasks.Task RevertAllFileContentStreamsAsync() {
            return base.Channel.RevertAllFileContentStreamsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CustomizeCssResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.CustomizeCssAsync(Rohi.EBinder.Sync.WebsReference.CustomizeCssRequest request) {
            return base.Channel.CustomizeCssAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.CustomizeCssResponse> CustomizeCssAsync(string cssFile) {
            Rohi.EBinder.Sync.WebsReference.CustomizeCssRequest inValue = new Rohi.EBinder.Sync.WebsReference.CustomizeCssRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.CustomizeCssRequestBody();
            inValue.Body.cssFile = cssFile;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).CustomizeCssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertCssResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.RevertCssAsync(Rohi.EBinder.Sync.WebsReference.RevertCssRequest request) {
            return base.Channel.RevertCssAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.RevertCssResponse> RevertCssAsync(string cssFile) {
            Rohi.EBinder.Sync.WebsReference.RevertCssRequest inValue = new Rohi.EBinder.Sync.WebsReference.RevertCssRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.RevertCssRequestBody();
            inValue.Body.cssFile = cssFile;
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).RevertCssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesResponse> Rohi.EBinder.Sync.WebsReference.WebsSoap.GetActivatedFeaturesAsync(Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequest request) {
            return base.Channel.GetActivatedFeaturesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesResponse> GetActivatedFeaturesAsync() {
            Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequest inValue = new Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequest();
            inValue.Body = new Rohi.EBinder.Sync.WebsReference.GetActivatedFeaturesRequestBody();
            return ((Rohi.EBinder.Sync.WebsReference.WebsSoap)(this)).GetActivatedFeaturesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.WebsSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.WebsSoap)) {
                return new System.ServiceModel.EndpointAddress("http://spweb.local/_vti_bin/webs.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return WebsSoapClient.GetBindingForEndpoint(EndpointConfiguration.WebsSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return WebsSoapClient.GetEndpointAddress(EndpointConfiguration.WebsSoap);
        }
        
        public enum EndpointConfiguration {
            
            WebsSoap,
        }
    }
}
